services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: docker:docker
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/data/docker/volumes/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: docker:docker
    environment:
      - TZ=America/New_York
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD} 
    volumes:
      - /mnt/data/docker/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
