version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - PUID=996
      - PGID=988
      - TZ=America/New_York
    volumes:
      - /mnt/data/docker/volumes/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    
  grafana:
  image: grafana/grafana
  container_name: grafana
  environment:
      - PUID=996
      - PGID=988
      - TZ=America/New_York
  volumes:
    - /mnt/data/docker/volumes/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD} 
  ports:
    - "3000:3000"
  restart: unless-stopped
